"""
Standard footer for public bot comments.
Idempotent: appends footer only once, replaces old footer format.
"""

import re

BOT_COMMENT_FOOTER = "*^(AI assistant · generated by Optimist Prime)*"

# Match both the legacy summon footer and the current non-triggering footer.
CURRENT_FOOTER_REGEX = re.compile(
    r"\*+\^?\(AI assistant · (?:mention the bot, mod bot, or use !bot|generated by Optimist Prime)\)\*+",
    re.IGNORECASE,
)


def format_bot_comment(body: str) -> str:
    """Append the standard footer once (idempotent if already present)."""
    trimmed = body.rstrip()
    match = CURRENT_FOOTER_REGEX.search(trimmed)
    if match:
        before_footer = trimmed[: match.start()].rstrip("\n- ").rstrip()
        return f"{before_footer}\n\n---\n{BOT_COMMENT_FOOTER}"
    return f"{trimmed}\n\n---\n{BOT_COMMENT_FOOTER}"


def strip_bot_footer(text: str) -> str:
    """Remove current or legacy bot footers before summon detection."""
    without_footer = CURRENT_FOOTER_REGEX.sub("", text)
    without_separator = re.sub(r"\n\s*---\s*$", "", without_footer)
    return without_separator.strip()
